language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    - addon-google_apis-google-27
script:
 - cd Labs
 - chmod +x gradlew
 - if [[ $LINT == 'true' ]]; then ./gradlew lint ; fi
deploy:
  provider: releases
  api_key:
    secure: ${API_KEY}
  file: "app/build/outputs/apk/debug/app-debug.apk"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
